{{- range .Values.llms }}
{{- $modelVolume := .modelName | lower | replace "/" "-" | replace "." "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-{{ $modelVolume }}
  namespace: cyber-ai
spec:
  replicas: {{ .replicaCount | default 1 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vllm-{{ $modelVolume }}
  template:
    metadata:
      labels:
        app: vllm-{{ $modelVolume }}
    spec:
      runtimeClassName: nvidia 

      imagePullSecrets:
        - name: {{ $.Values.artifactory.ARTIFACTORY_SECRET }}
            
      nodeSelector:
        {{- toYaml (default $.Values.nodeSelector .nodeSelector) | nindent 8 }}

      tolerations:
        {{- toYaml (default $.Values.tolerations .tolerations) | nindent 8 }}

      containers:
      - name: vllm-gpu
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy | default "IfNotPresent" }}
        command: {{ .command | default (list "vllm") | toJson }}
        args:
          {{- toYaml .args | nindent 10 }}

        resources:
          limits:
            nvidia.com/gpu: {{ .hardware.gpuLimit | quote }}
          requests:
            nvidia.com/gpu: {{ .hardware.gpuLimit | quote }}
            
        env:
        - name: HF_HOME
          value: "/root/.cache/huggingface"
        - name: HF_HUB_ETAG_TIMEOUT
          value: "86400"
        - name: HF_HUB_DOWNLOAD_TIMEOUT
          value: "86400"
        - name: HF_ENDPOINT
          value: {{ $.Values.artifactory.HF_ENDPOINT | quote }}
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.artifactory.HF_TOKEN | quote }} 
              key: "token" 

        ports:
        {{- range .ports | default (list 8000) }}
        - containerPort: {{ . }}
        {{- end }}

        volumeMounts:
        - name: model-storage
          mountPath: /root/.cache/huggingface 
        - name: dshm
          mountPath: /dev/shm 

      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: pvc-vllm-cache-{{ $modelVolume }}
      - name: dshm
        emptyDir:
          medium: Memory
---
{{- end }}