# To avoid downloading the weights every time a pod starts/restarts
# Weights are saved into the cluster

{{- range .Values.llms }}
{{- $modelVolume := .modelName | lower | replace "/" "-" | replace "." "-" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vllm-cache-{{ $modelVolume }}
  namespace: cyber-ai
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: {{ $.Values.storage.className }}
  resources:
    requests:
      storage: {{ .storageSize | default "100Gi" }} 
---
{{- end }}