apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.yaml: |
    model_list:
      - model_name: Qwen2.5-0.5B-Instruct-cpu
        litellm_params:
          model: openai/Qwen/Qwen2.5-0.5B-Instruct
          api_base: http://vllm-cpu-qwen-qwen2-5-0-5b-instruct-service:8000/v1 # Qwen/Qwen2.5-0.5B-Instruct-service 
          api_key: not-needed
    router_settings:
      routing_strategy: least-busy
      num_retries: 0
      routing_strategy_args:
          dns_routing: true